---
server.port: 8001

## to access the git file in repository
## the searchPaths value the folder base to search
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ailtonmsj/ConfigDataSpringCloud1
          searchPaths: ConfigData

## exposes some endpoints from actuator
management.endpoints.web.exposure.include: bus-refresh,info,health